// <auto-generated />
namespace Scrummage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DoneAtPropertyAddedToScrumTasksTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoneAtPropertyAddedToScrumTasksTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711062046326_DoneAtPropertyAddedToScrumTasksTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
